[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/**"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Enable Next.js Image Optimization
[images]
  remote_images = ["https://cdn.sanity.io/.*"]
