[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Edge Functions
[[edge_functions]]
  path = "/api/revalidate"
  function = "revalidate"

# Enable Next.js Image Optimization
[images]
  remote_images = ["https://cdn.sanity.io/.*"]
